# Default settings used throughout this Nix flake

[user]
name = "seh"
fullName = "Steven E. Harris"
homeDirectory = "/home/seh"
email = "seh@panix.com"
# TODO(seh): gpgKey = "..."

# NB: It's a good idea to override this option this per host.
#
# https://nix-community.github.io/home-manager/options.html#opt-home.stateVersion
stateVersion = "23.05"

[user.darwin]
homeDirectory = "/Users/seh"

[os]
system = "x86_64-linux"

# NB: It's a good idea to override this option this per host.
#
# https://nix-community.github.io/home-manager/options.html#opt-home.stateVersion
stateVersion = "25.11"

[os.darwin]
system = "x86_64-darwin"

# NB: It's a good idea to override this option this per host.
#
# https://daiderd.com/nix-darwin/manual/index.html#opt-system.stateVersion
stateVersion = 6

[nix]
package = "latest" # Example alternative: "nix_2_13"
