setopt extendedglob
# NB: Home Manager does not offer an analog to its
# "programs.zsh.autocd" attribute for this, and oh-my-zsh enables this
# by default in its "lib/directories.zsh" file:
# https://github.com/ohmyzsh/ohmyzsh/blob/de1ca65dcaebd19f5ca6626616bb79b529362458/lib/directories.zsh#L3
unsetopt auto_pushd

# fzf configuration
export FZF_COMPLETION_TRIGGER='~~'

_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    cd)           fzf "$@" --preview 'tree -C {} | head -200' ;;
    export|unset) fzf "$@" --preview "eval 'echo \$'{}" ;;
    ssh)          fzf "$@" --preview 'ranswer=$(dig -x {} +short); if [ -n "${ranswer}" ]; then echo "${ranswer}"; else dig +noall +answer +nottlid +noclass {}; fi' ;;
    *)            fzf "$@" ;;
  esac
}

# To customize the  prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [ -f ~/.p10k.zsh ]; then
  source ~/.p10k.zsh
fi

# Other programs

# Work around the zsh completion command for the "aws" tool not being
# amenable to "autoload", per
# https://github.com/NixOS/nixpkgs/issues/275770:
if command -v aws > /dev/null 2>&1; then
  for p in ${(ps. .)NIX_PROFILES}; do
    f="${p}/share/zsh/site-functions/_aws"
    if [ -r "${f}" ]; then
      source "${f}"
      break
    fi
  done
fi
